export const experiences = [
  {
    title: "SDE-1",
    company_name: "Spinny",
    icon: "images/spinny-logo.png",
    iconBg: "#d1e8ff",
    date: "Aug 2025 – Present",
    points: [
      "Led frontend migration from React 17 to React 19, improving rendering efficiency and boosting overall performance by ~11%.",
      "Built a car comparison feature enabling multi-parameter filtering, increasing test drive bookings and conversions by 8%.",
      "Developed a personalized Buy Homepage using user behavior data, improving listing relevance and driving 4–5% higher sales.",
      "Implemented early loan profiling on listing pages, increasing financial intent capture by 4%.",
      "Automated city-service mapping via CMS, eliminating manual configuration and reducing go-live time across cities.",
      "Designed a scalable design system using Razorpay Blade, reducing feature delivery time by 18% and improving UI consistency.",
      "Tech Stack: React.js, Next.js, TypeScript, Tailwind CSS, Express.js, Redis, Vite, Webpack | Rendering: SSR, CSR, SSG",
    ],
  },
  {
    title: "Associate Software Developer",
    company_name: "Internshala",
    icon: "https://internshala.com/assets/images/internshala_logo.svg",
    iconBg: "#e0f7fa",
    date: "Oct 2023 – Aug 2025",
    points: [
      "Migrated legacy PHP pages to Next.js, improving performance by 15% and reducing bugs by 40%+.",
      "Implemented RabbitMQ-based email batching, reducing server load and improving delivery efficiency by 30%.",
      "Built a WebSocket-based real-time chat system handling 1000+ concurrent users during live events with minimal latency.",
      "Integrated Paynimo payment gateway, improving transaction reliability and reducing dependency on existing providers.",
      "Implemented Elasticsearch-powered multi-search, improving query performance by 28%.",
      "Refactored legacy code into modular architecture, improving maintainability and reducing future development effort.",
      "Tech Stack: Next.js, React.js, PHP, RabbitMQ, Elasticsearch, WebSocket, TypeScript, Tailwind CSS.",
    ],
  },
  {
    title: "Software Developer Intern",
    company_name: "Wabi Tech",
    icon: "",
    iconBg: "#ffe0b2",
    date: "Oct 2021 – Dec 2021",
    points: [
      "Identified and resolved 5+ critical bugs through manual testing, reducing user drop rate by 10%.",
      "Improved mobile app responsiveness and performance through feature optimization.",
      "Built group creation and management functionality, enabling private user communities.",
      "Collaborated with UI/UX team to improve interaction flows, increasing daily group engagement by 15%.",
      "Developed modular Python scripts to support backend operations and API integrations.",
      "Tech Stack: Python, Manual Testing, Mobile App Development.",
    ],
  },
];